version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    build: ./web
    environment:
      - NODE_ENV=development
    volumes:
      - ./web:/usr/src/app
    # command: npm start
    ports:
      - 3001:3000
    tty: true
    stdin_open: true

  api:
    build: ./api
    ports:
      - 3000:3000
    volumes :
      - ./api:/api
    # command: yarn nodemon
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - default

  db:
    build: ./db
    restart: always
    ports:
      - 3300:3306
    # volumes:
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./db/init_db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=27822750
      - MYSQL_DATABASE=login_db
      - HOST=db
      - MYSQL_USER=root
      - ./db/env
    networks:
      - default